-- StackMatch Seed Data
-- Run after schema.sql

insert into vendors (name, slug, category, tagline, color, website_url,
  pos_integrations, problem_tags, venue_types,
  stat_1_val, stat_1_lbl, stat_2_val, stat_2_lbl, stat_3_val, stat_3_lbl,
  hook, is_verified)
values

-- LABOUR
('Rotaready', 'rotaready', 'Workforce Management',
  'UK-built rota software that actually understands hospitality shift patterns and compliance.',
  '#5B4FC4', 'https://rotaready.com',
  array['zonal','lightspeed','square','other'],
  array['labour'],
  array['pub','restaurant','hotel','casual-dining'],
  '£12k', 'avg annual saving', '4.5★', 'G2 rating', '2hrs', 'saved per week',
  'Built by operators who got fed up with Excel rotas at 2am.', true),

('Fourth', 'fourth', 'Workforce Management',
  'Enterprise-grade scheduling and labour analytics used by most of the UK''s big casual dining groups.',
  '#E64E1A', 'https://fourth.com',
  array['oracle','zonal','lightspeed','other'],
  array['labour'],
  array['casual-dining','enterprise','hotel'],
  '30%', 'labour cost reduction', '10k+', 'venues globally', 'Full', 'payroll integration',
  'If you''re running 5+ sites and still doing rotas in sheets, this is the conversation to have.', true),

('Planday', 'planday', 'Scheduling',
  'Shift planning with staff app, comms and payroll built in. Strong with cafés and SME operators.',
  '#0074D9', 'https://planday.com',
  array['square','lightspeed','vita','other'],
  array['labour'],
  array['cafe','restaurant','qsr'],
  '3min', 'avg rota build time', 'ISO', 'certified', '50+', 'payroll integrations',
  'Your team gets an app. You get your Sunday evenings back.', true),

('Deputy', 'deputy', 'Scheduling',
  'Demand-based scheduling with AI shift suggestions built from your actual trading data.',
  '#00B4D8', 'https://deputy.com',
  array['square','lightspeed','vita','other'],
  array['labour'],
  array['qsr','cafe','restaurant'],
  'AI', 'demand forecasting', 'Free', 'app for staff', '24/7', 'support',
  'Uses your trading data to suggest who you actually need, not who you think you need.', true),

-- WASTE / MARGINS
('Tenzo', 'tenzo', 'Analytics & Margin',
  'Live P&L visibility across all your sites. Pulls from your POS, labour and purchasing in one dashboard.',
  '#00B4D8', 'https://gotenzo.com',
  array['lightspeed','square','zonal','vita','oracle','other'],
  array['waste','data'],
  array['casual-dining','qsr','hotel','enterprise'],
  '2%', 'avg margin improvement', 'Real-time', 'P&L', '150+', 'integrations',
  'Finally know if today was actually a good day or just a busy one.', true),

('Winnow', 'winnow', 'Food Waste',
  'AI camera that sits on your kitchen bins and measures exactly what you''re throwing away.',
  '#2ECC71', 'https://winnowsolutions.com',
  array['oracle','zonal','lightspeed','other'],
  array['waste'],
  array['hotel','enterprise','casual-dining'],
  '50%', 'waste reduction', '£50k+', 'avg annual saving', 'AI', 'ingredient ID',
  'IKEA, IHG and Marriott use it. Chances are your bins are hiding a headcount.', true),

('Nory', 'nory', 'Inventory & Forecasting',
  'AI-first restaurant OS that handles ordering, recipes, forecasting and margin all in one.',
  '#9B59B6', 'https://nory.ai',
  array['square','lightspeed','vita','other'],
  array['waste','data'],
  array['qsr','casual-dining','restaurant'],
  'AI', 'demand forecasting', '2–5%', 'margin recovery', 'Auto', 'purchase ordering',
  'Not just a tracker. It orders for you based on what it predicts you''ll sell.', true),

('MarketMan', 'marketman', 'Inventory Management',
  'Cloud-based inventory with real-time COGS and supplier management. Popular with independents.',
  '#E67E22', 'https://marketman.com',
  array['square','lightspeed','other'],
  array['waste'],
  array['restaurant','cafe','bar'],
  'COGS', 'real-time tracking', '95%', 'order accuracy', '500+', 'UK venues',
  'If your chef is still doing stock takes on a clipboard, here''s the conversation to start.', true),

-- BOOKINGS
('SevenRooms', 'sevenrooms', 'Reservations & CRM',
  'Reservations, waitlist, CRM and marketing in one platform. Built for operators who take hospitality seriously.',
  '#E64E1A', 'https://sevenrooms.com',
  array['oracle','zonal','lightspeed','other'],
  array['bookings','loyalty'],
  array['restaurant','hotel','enterprise'],
  '30%', 'no-show reduction', 'Auto', 'pre-auth deposits', 'Full', 'CRM built-in',
  'The guest who visited 3 months ago gets recognised on arrival. That''s the standard to aim for.', true),

('Resy', 'resy', 'Reservations',
  'Consumer-facing booking platform used by high-profile independents and groups across the UK.',
  '#FF6B6B', 'https://resy.com',
  array['lightspeed','square','other'],
  array['bookings'],
  array['restaurant','bar'],
  'Freemium', 'model available', 'Network', 'discovery traffic', 'Mobile', 'first',
  'Your venue listed on Resy is a signal to a certain type of guest that you take things seriously.', true),

('OpenTable', 'opentable', 'Reservations',
  'Largest global diner network. High distribution but comes with cover fees operators need to weigh up.',
  '#DA3743', 'https://opentable.co.uk',
  array['zonal','lightspeed','oracle','square','vita','other'],
  array['bookings'],
  array['restaurant','hotel','pub','casual-dining'],
  '36m+', 'diners globally', 'Cover', 'fee model', 'POS', 'sync available',
  'Volume is there. The question is whether the cover fees make sense for your margin.', true),

('Tock', 'tock', 'Reservations & Ticketing',
  'Pre-payment and deposit-first booking. Basically eliminates no-shows by design.',
  '#2C3E50', 'https://exploretock.com',
  array['lightspeed','square','other'],
  array['bookings'],
  array['restaurant','bar'],
  'Near 0%', 'no-show rate', 'Pre-pay', 'by design', 'Events', 'ticketing too',
  'If a no-show costs you £200 per cover, pre-payment isn''t a luxury. It''s risk management.', true),

-- LOYALTY
('Airship', 'airship', 'CRM & Marketing',
  'UK-built CRM for hospitality. Guest data, segmentation and targeted campaigns from your POS.',
  '#3498DB', 'https://airship.co.uk',
  array['zonal','lightspeed','square','other'],
  array['loyalty'],
  array['pub','casual-dining','bar','restaurant'],
  'UK-built', 'for hospitality', 'Real-time', 'guest profiles', 'Email + SMS', 'included',
  'Know which guests haven''t been in for 6 weeks. Send them a reason to come back.', true),

('Yumpingo', 'yumpingo', 'Guest Intelligence',
  'Real-time dish-level feedback captured at the moment of payment. Find out what''s actually good.',
  '#16A085', 'https://yumpingo.com',
  array['zonal','lightspeed','square','vita','oracle','other'],
  array['loyalty','data'],
  array['casual-dining','qsr','hotel','restaurant'],
  'Dish-level', 'feedback', 'Real-time', 'alerts', 'NPS', 'benchmarking',
  'Your chefs will love this. Or hate it. Either way, you''ll finally know the truth about that pasta.', true),

-- OPS
('Trail', 'trail', 'Operations',
  'Digital ops platform replacing paper checklists, food safety logs and daily team comms.',
  '#27AE60', 'https://trail.app',
  array['zonal','lightspeed','square','vita','oracle','other'],
  array['ops'],
  array['pub','restaurant','hotel','cafe','qsr'],
  'HACCP', 'compliant', '2min', 'daily setup', 'UK-built', 'for hospitality',
  'Your opening manager shouldn''t need a clipboard and a prayer. Trail sorts that.', true),

('Harri', 'harri', 'Team & HR',
  'Hiring, onboarding, team comms and scheduling in one HR platform built for hospitality.',
  '#E74C3C', 'https://harri.com',
  array['zonal','lightspeed','oracle','square','other'],
  array['ops','labour'],
  array['casual-dining','hotel','enterprise'],
  'Recruiting', 'built in', 'Auto', 'onboarding', 'Comms', '& engagement',
  'From job post to first shift to performance review. One place for all of it.', true),

('Checkit', 'checkit', 'Compliance & Ops',
  'IoT-connected food safety monitoring. Sensors and software for temperature, checklists and audits.',
  '#1ABC9C', 'https://checkit.net',
  array['oracle','zonal','lightspeed','other'],
  array['ops'],
  array['hotel','enterprise','casual-dining'],
  'IoT', 'sensors', 'Auto', 'temp logging', 'Audit', 'ready reports',
  'When an EHO walks in unannounced, you want your temperature logs to be automatic, not hopeful.', true);
